---
title: "DATest"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
if (!requireNamespace("Giotto", quietly = TRUE))
  devtools::install_github("drieslab/Giotto@suite")
library(Giotto)
library(ggplot2)
library(ggpubr)
```

## Configuring Giotto package and raw data

Checking if miniconda and python is in place

```{r}
# configure Giotto
genv_exists = checkGiottoEnvironment()
print(genv_exists)
if(!genv_exists){
  # The following command need only be run once to install the Giotto environment.
  installGiottoEnvironment()
}
```

## Import raw data

```{r}
datax <- read.csv("../../data/Sandy_MELC_Mouse/MELC_data_murine_lung_CTRL_D1_D2_D3_withfolders.csv")
samples <- unique(datax$FullInfo)
samples <- samples[!samples %in% "20210906_FOV3_D3"]
gio_list <- NULL
for(samp in samples){

  # cur_datax
  cur_datax <- datax[datax$FullInfo == samp,]
  
  # sample and image folder
  image_folder <- unique(cur_datax$Sample)
  print(image_folder)

  # data
  cur_data <- cur_datax[,2:34]
  rownames(cur_data) <- cur_datax$CellID
  cur_data <- t(cur_data)

  # metadata
  cur_metadata <- cur_datax[,38:46]
  rownames(cur_metadata) <- cur_datax$CellID

  # coordinates
  cur_coords <- cur_datax[,c("Loc_X", "Loc_Y")]
  rownames(cur_coords) <- cur_datax$CellID

  # main giotto object
  gio_list[[image_folder]] <- createGiottoObject(expression = cur_data, spatial_locs = cur_coords)

  # metadata
  gio_list[[image_folder]] <- addCellMetadata(gobject =  gio_list[[image_folder]], new_metadata = cur_metadata)

  # make delaunay graph
  gio_list[[image_folder]] <- createSpatialDelaunayNetwork(gio_list[[image_folder]])
}
# saveRDS(gio_list, file = "data/Giotto_data_sandy.rds")
```
