#' generateSegments_old
#'
#' The function to import segments from a geojson file
#'
#' @param geojson.file the GeoJSON file, typically generated by QuPath software
#'
#' @importFrom rjson fromJSON
#' @importFrom dplyr tibble
#'
#' @noRd
generateSegments_old <- function(geojson.file) {
  # get segments
  if (inherits(geojson.file, "character")) {
    if (file.exists(geojson.file)) {
      segments <- rjson::fromJSON(file = geojson.file)
    } else {
      stop("geojson.file doesn't exist!")
    }
  } else {
    stop("geojson.file should be the path to the GeoJSON file!")
  }

  # parse polygons as segments/ROIs
  segments <- lapply(segments, function(x) {
    type <- x$geometry$type
    poly <- x$geometry$coordinates
    if (grepl("Polygon", type)) {
      poly <- as.data.frame(matrix(unlist(poly[[1]]), ncol = 2, byrow = TRUE))
    }
    colnames(poly) <- c("x", "y")
    dplyr::tibble(poly)
  })

  # attach names to segments
  segments <- mapply(
    function(x, sgt) {
      dplyr::tibble(data.frame(id = x, sgt))
    },
    seq_len(length(segments)),
    segments,
    SIMPLIFY = FALSE
  )

  # generate ROI names
  names(segments) <- paste0("ROI", seq_len(length(segments)))

  # return
  return(segments)
}

#' generateGeoJSON_old
#'
#' Old version: generating geojson files from segments
#'
#' @param segments the segments, typically from \link{vrSegments}.
#' @param file the GeoJSON file, typically to be used by QuPath software.
#'
#' @noRd
generateGeoJSON_old <- function(segments, file) {
  if (!requireNamespace('geojsonR')) {
    stop("Please install geojsonR package for using geojsonR functions: ", 
         "install.packages('geojsonR')")
  }
  
  # get segments
  if (!inherits(file, "character")) {
    stop("file should be the path to the GeoJSON file!")
  }
  
  # reshape segments
  segments <- mapply(
    function(id, sgt) {
      poly <- na.omit(as.matrix(sgt[, c("x", "y")]))
      poly <- rbind(poly, poly[1, , drop = FALSE])
      poly <- as.list(data.frame(t(poly)))
      names(poly) <- NULL
      init <- geojsonR::TO_GeoJson$new()
      geometry <- init$Polygon(list(poly), stringify = TRUE)
      feature <- list(
        type = "Feature",
        id = id,
        geometry = geometry[!names(geometry) %in% "json_dump"],
        properties = list(objectType = "annotation")
      )
      feature
    },
    names(segments),
    segments,
    SIMPLIFY = FALSE,
    USE.NAMES = FALSE
  )
  
  # save as json
  segments <- rjson::toJSON(segments)
  write(segments, file = file)
}