# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

automated_registeration_rawvector <- function(ref_image, query_image, width1, height1, width2, height2, invert_query, invert_ref, flipflop_query, flipflop_ref, rotate_query, rotate_ref) {
    .Call('_VoltRon_automated_registeration_rawvector', PACKAGE = 'VoltRon', ref_image, query_image, width1, height1, width2, height2, invert_query, invert_ref, flipflop_query, flipflop_ref, rotate_query, rotate_ref)
}

perspectiveTransform <- function(coords, hmatrix) {
    .Call('_VoltRon_perspectiveTransform', PACKAGE = 'VoltRon', coords, hmatrix)
}

calculateMoransI <- function(data, datadist, sumW) {
    .Call('_VoltRon_calculateMoransI', PACKAGE = 'VoltRon', data, datadist, sumW)
}

