# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accuracy_rawvector <- function(ref_image, query_image, mask, width, height, type, overlay_images = TRUE, compute_matte_map = TRUE) {
    .Call('_VoltRon_accuracy_rawvector', PACKAGE = 'VoltRon', ref_image, query_image, mask, width, height, type, overlay_images, compute_matte_map)
}

automated_registeration_rawvector <- function(ref_image, query_image, width1, height1, width2, height2, GOOD_MATCH_PERCENT, MAX_FEATURES, invert_query, invert_ref, flipflop_query, flipflop_ref, rotate_query, rotate_ref, matcher, method, nonrigid, compute_matte_map = TRUE) {
    .Call('_VoltRon_automated_registeration_rawvector', PACKAGE = 'VoltRon', ref_image, query_image, width1, height1, width2, height2, GOOD_MATCH_PERCENT, MAX_FEATURES, invert_query, invert_ref, flipflop_query, flipflop_ref, rotate_query, rotate_ref, matcher, method, nonrigid, compute_matte_map)
}

replaceNaMatrix <- function(mat, replace) {
    .Call('_VoltRon_replaceNaMatrix', PACKAGE = 'VoltRon', mat, replace)
}

warpRcppImage <- function(ref_image, query_image, mapping, width1, height1, width2, height2) {
    .Call('_VoltRon_warpRcppImage', PACKAGE = 'VoltRon', ref_image, query_image, mapping, width1, height1, width2, height2)
}

warpImageAuto <- function(ref_image, query_image, mapping, width1, height1, width2, height2) {
    .Call('_VoltRon_warpImageAuto', PACKAGE = 'VoltRon', ref_image, query_image, mapping, width1, height1, width2, height2)
}

warpImageManual <- function(ref_image, query_image, mapping, width1, height1, width2, height2) {
    .Call('_VoltRon_warpImageManual', PACKAGE = 'VoltRon', ref_image, query_image, mapping, width1, height1, width2, height2)
}

manual_registeration_rawvector <- function(ref_image, query_image, reference_landmark, query_landmark, width1, height1, width2, height2, invert_query, invert_ref, method, nonrigid, compute_matte_map = TRUE) {
    .Call('_VoltRon_manual_registeration_rawvector', PACKAGE = 'VoltRon', ref_image, query_image, reference_landmark, query_landmark, width1, height1, width2, height2, invert_query, invert_ref, method, nonrigid, compute_matte_map)
}

manual_registeration_matrix <- function(query_data, reference_landmark, query_landmark, method, nonrigid) {
    .Call('_VoltRon_manual_registeration_matrix', PACKAGE = 'VoltRon', query_data, reference_landmark, query_landmark, method, nonrigid)
}

applyRcppMapping <- function(coords, mapping) {
    .Call('_VoltRon_applyRcppMapping', PACKAGE = 'VoltRon', coords, mapping)
}

generateOverlapMask <- function(dsize, trans_mat, ssize) {
    .Call('_VoltRon_generateOverlapMask', PACKAGE = 'VoltRon', dsize, trans_mat, ssize)
}

build_snn_rank <- function(neighbors) {
    .Call('_VoltRon_build_snn_rank', PACKAGE = 'VoltRon', neighbors)
}

build_snn_number <- function(neighbors) {
    .Call('_VoltRon_build_snn_number', PACKAGE = 'VoltRon', neighbors)
}

replacePatternInRcppVectorWrapper <- function(textVector, pattern, replacement) {
    .Call('_VoltRon_replacePatternInRcppVectorWrapper', PACKAGE = 'VoltRon', textVector, pattern, replacement)
}

