# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

automated_registeration_rawvector <- function(ref_image, query_image, width1, height1, width2, height2, GOOD_MATCH_PERCENT, MAX_FEATURES, invert_query, invert_ref, flipflop_query, flipflop_ref, rotate_query, rotate_ref, matcher, method) {
    .Call('_VoltRon_automated_registeration_rawvector', PACKAGE = 'VoltRon', ref_image, query_image, width1, height1, width2, height2, GOOD_MATCH_PERCENT, MAX_FEATURES, invert_query, invert_ref, flipflop_query, flipflop_ref, rotate_query, rotate_ref, matcher, method)
}

replaceNaMatrix <- function(mat, replace) {
    .Call('_VoltRon_replaceNaMatrix', PACKAGE = 'VoltRon', mat, replace)
}

warpImage <- function(ref_image, query_image, mapping, width1, height1, width2, height2) {
    .Call('_VoltRon_warpImage', PACKAGE = 'VoltRon', ref_image, query_image, mapping, width1, height1, width2, height2)
}

warpImageAuto <- function(ref_image, query_image, mapping, width1, height1, width2, height2) {
    .Call('_VoltRon_warpImageAuto', PACKAGE = 'VoltRon', ref_image, query_image, mapping, width1, height1, width2, height2)
}

warpImageManual <- function(ref_image, query_image, mapping, width1, height1, width2, height2) {
    .Call('_VoltRon_warpImageManual', PACKAGE = 'VoltRon', ref_image, query_image, mapping, width1, height1, width2, height2)
}

manual_registeration_rawvector <- function(ref_image, query_image, reference_landmark, query_landmark, width1, height1, width2, height2, method) {
    .Call('_VoltRon_manual_registeration_rawvector', PACKAGE = 'VoltRon', ref_image, query_image, reference_landmark, query_landmark, width1, height1, width2, height2, method)
}

applyMapping <- function(coords, mapping) {
    .Call('_VoltRon_applyMapping', PACKAGE = 'VoltRon', coords, mapping)
}

build_snn_rank <- function(neighbors) {
    .Call('_VoltRon_build_snn_rank', PACKAGE = 'VoltRon', neighbors)
}

build_snn_number <- function(neighbors) {
    .Call('_VoltRon_build_snn_number', PACKAGE = 'VoltRon', neighbors)
}

replacePatternInRcppVectorWrapper <- function(textVector, pattern, replacement) {
    .Call('_VoltRon_replacePatternInRcppVectorWrapper', PACKAGE = 'VoltRon', textVector, pattern, replacement)
}

